### ISSUE TITLE
小程序“提示收藏”功能

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#1056]
近期，（应该是）得益于在福州晚报的“福州腔调”微信推送中嵌入榕典小程序链接，我们偶尔会有访问“小高峰”。

比如说今天有120人打开榕典小程序（一般的日子小几十人，所以120人已经算高峰了）。但是这个“高峰”很快过去，基本没有回头客。（工具性的app，这样也是正常的；因为平常查词的需求不频繁，下次想查的时候也不记得榕典了）

如何【留存】这些用户？我觉得一个方法是提示用户收藏，如其他小程序做的：

![image](https://user-images.githubusercontent.com/2714446/105044053-3cba2a00-5aa1-11eb-9d80-39ed670df17f.png)

**Comment by Guanchishan** [comment]
這個方法不錯
