### ISSUE TITLE
lou还是duo

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/yngdieng#106]
**词条网址**

http://yngdieng-staging.mindong.asia/feng/p403_12

**错误之处**？
> 泥水滿地，濕：許條路～，儥行過(無法走過去)

路，不太确定是否该作duo。

**Comment by ztl8702** [comment]
应该是是duo

**Comment by DDFShanyu** [comment]
榕典duo这个词是按冯书写成路，没有录墿这个字
有一种观点是duo本字就是路，跟蛎读成die一样，冯书应该就是这个观点

**Comment by ztl8702** [comment]
（有疑问再开）
