### ISSUE TITLE
Unable to load shared library 'libopencc.so.1.1.1' 

### ISSUE THREAD

**Issue by insualk** [MindongLab/yngdieng#1111]
运行`dotnet run -p server/indexer/Yngdieng.Indexer.csproj -- ../../data ../../output`时报错：

> Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libopencc.so.1.1.1' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibopencc.so.1.1.1, 1): image not found

在`Yngdieng.Opencc`里面确实有看到`libopencc.so.1.1.1`。刚刚查了好久，但是感觉完全没头绪……

**Comment by ztl8702** [comment]
因为我当时懒得加macOS 的 libopencc （只加了Linux的 native image）。现在最快的 workaround，可以是直接去下载我们线上的index，放到 output 目录下.

https://ztl8702.visualstudio.com/YngdiengPrivate/_build/results?buildId=1052&view=artifacts&pathAsName=false&type=publishedArtifacts （如果需要权限请告诉我，我也会发email给你一份）

**Comment by ztl8702** [comment]
Is this resolved?

**Comment by insualk** [comment]
Yes. Thank you.

**Comment by ztl8702** [comment]
你有在修改backend吗？如果只是改动前端的话，不需要在本地跑backend，只要把
https://github.com/MindongLab/yngdieng/blob/9afebfe76522de25e500d659030aacc6663cd40a/web/src/environments/environment.dev.ts#L9
uncomment 掉就行。

**Comment by insualk** [comment]
是，我现在都是直接用远端的api。没有在修改backend。上次只是想着试下用本地的后端跑一下。
