### ISSUE TITLE
UI内添加“推荐用字”标识

### ISSUE THREAD

**Issue by ZySieng** [MindongLab/yngdieng#1118]
如下，该条目内各个来源用字不同，与顶部的推荐用字差异大，会造成用户的困惑
https://staging.ydict.net/w/CgM4RTU
这时候，应该在条目用字前（即大字前）加入“推荐用字”四字，与下方拼音前的“福州市区”、“市区单字”、“市区连读”一样
这样子汉字拼音对其了看过去也很爽

**Comment by ztl8702** [comment]
推荐用字 or 榕典推荐用字？

**Comment by ZySieng** [comment]
推荐用字 四字吧
榕典里面见到的推荐用字 就是榕典推荐用字了 不用重复

**Comment by ZySieng** [comment]
![image](https://user-images.githubusercontent.com/32233404/112856105-0a9cf800-90e2-11eb-80a3-4a831e241855.png)
写 推荐用字 比较好，打成了 推荐汉字
另外就是，我感觉ui这么排看着有点不和谐，“无这无许”应该放在“推荐用字”右边

**Comment by ZySieng** [comment]
小程序的“推荐用字”写成了“推荐汉字”。
刚刚的图给错了，我把前一楼删了。
