### ISSUE TITLE
去除feng文本中的多余空格

### ISSUE THREAD

**Issue by ZySieng** [MindongLab/yngdieng#1248]
**问题描述**
feng文本中有很多多余的空格。在用户搜索时会看见，不美观。

如
【便】	bieng242	bieng242	①方便，便利：有～去②現 成的；簡單平常的：～～飯食𡅏去|～ 菜
这里的“現 成的”

这些是厝边网当时遗留的问题
能不能想个办法把这些空格在文本层面都去掉，直接批量替换会把拼音的空格也去掉。也就是说要从每个条目第三个制表符开始批量替换

**Comment by ztl8702** [comment]
Fixed in https://github.com/ztl8702/zingzeu-data/commit/ceb5973f9b8c2268d628a5d221e875bc539e831e
