### ISSUE TITLE
字典的数据是从哪里来的？

### ISSUE THREAD

**Issue by programmeruser2** [MindongLab/yngdieng#1314]

**Comment by ztl8702** [comment]
来自 https://www.ydict.net/help

> 文献来源
> 已上线（或部分上线）
>  * 冯爱珍 1998 《福州方言词典》，江苏教育出版社。
>  * 李如龙 王升魁校注 2001 《戚林八音校注》，福建人民出版社。
>  * R. S. Maclay & C. C. Baldwin & S. H. Leger, 1929, Dictionary of the Foochow Dialect, Presbyterian Mission Press of Shanghai.

**Comment by programmeruser2** [comment]
> 见 https://www.ydict.net/help ：
> 
> > 文献来源
> > 已上线（或部分上线）
> > 
> > * 冯爱珍 1998 《福州方言词典》，江苏教育出版社。
> > * 李如龙 王升魁校注 2001 《戚林八音校注》，福建人民出版社。
> > * R. S. Maclay & C. C. Baldwin & S. H. Leger, 1929, Dictionary of the Foochow Dialect, Presbyterian Mission Press of Shanghai.

你是怎么从纸书到程序可以用的数据？

**Comment by ztl8702** [comment]
人工手打

**Comment by ztl8702** [comment]
一众志愿者的付出 https://www.ydict.net/help/contributors

**Comment by KuroiRaku** [comment]
也想問一下你們會不會加入原本英文的翻譯？謝謝

**Comment by ztl8702** [comment]
> 也想問一下你們會不會加入原本英文的翻譯？謝謝

Dictionary of the Foochow Dialect 的英文部分，有。其实已经录了一部分了，需要人手来校对。你要自告奋勇吗？

**Comment by KuroiRaku** [comment]
可以幫忙校对，不過要怎樣幫我就不是很理解。 
畢竟還是第一次

**Comment by ztl8702** [comment]
> 可以幫忙校对，不過要怎樣幫我就不是很理解。 
> 
> 畢竟還是第一次 

可以把你的联系方式私发给我：ztl8702@msn.com
