### ISSUE TITLE
“犬雄”是否文雅

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/yngdieng#1339]
**词条网址**

https://www.ydict.net/w/CgQzNDJE

**争议之处**
![image](https://user-images.githubusercontent.com/30859354/129242451-1afbd8e0-2102-4926-90fc-87abc171153f.png)
注释写为“较文雅的说法”

**说明**

问了万物。他对犬雄这个词没有“更加文雅”的语感，而认为是同样地土。

来自长乐的Leo认为，如果一个动物既可说角，也可说雄，等等（如犬角、犬雄），则雄文雅（如犬雄比犬角文雅）。如果一个动物只有雄的说法，比如“鸭雄”，则无所谓文雅。

对于有些人觉得文雅而有些人觉得一般般的情况，@zysieng 认为是否需要加榕典注，来避免潜在的质疑？

**Comment by ZySieng** [comment]
没有必要。我觉得这些就不要开issue了，直接在群里说。
