### ISSUE TITLE
伲囝痞

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/yngdieng#1342]
山月(关彳山) 8-15 23:45:17
抄送万物意见：可以做在榕典做一个注，永泰人会把 伲囝痞 nie21-iang24-pi33 连读合音成 niang24-mi33

山月(关彳山) 8-15 23:45:38
福州腔调作者 天空树 音频就是这么读得

**Comment by ZySieng** [comment]
不需要写注，不是针对原书条目内容的修改

**Comment by ztl8702** [comment]
这个以后可以由万物自己写在评论区（看来有必要尽快弄一个评论区）

**Comment by Guanchishan** [comment]
也可以整一个 助记 的，助记内容由用户提交、投票

**Comment by Guanchishan** [comment]
参考：墨墨背单词的 用户自主提交助记 功能。
![image](https://user-images.githubusercontent.com/30859354/131782645-4c032c70-53f9-4ba4-8d38-d2ddbbe9120b.jpeg)![image](https://user-images.githubusercontent.com/30859354/131782646-c1d523da-2265-4590-8db3-7e8433291bbe.png)![image](https://user-images.githubusercontent.com/30859354/131782663-ab0da87f-cc25-4514-89ba-13f473a2e418.jpeg)![image](https://user-images.githubusercontent.com/30859354/131782671-3cda70be-5656-49d5-b377-df47d69f2da1.jpeg)
