### ISSUE TITLE
webfont support

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#15]

**Comment by ztl8702** [comment]
or use glyphwiki for unicode extension zones

**Comment by ztl8702** [comment]
决定采用webfont来支持扩展集显示。用类似Google Fonts所采用的字体切割方法。自行host webhost。


花园明朝字体： https://fonts.jp/hanazono/

**Comment by Guanchishan** [comment]
子善反映使用edge出现字体加载不全情况。
讨论认为墙内版的字体渲染服务也要用墙内的。
Ztl：没有（墙内的渲染服务）。但我们可以自己搭

**Comment by ztl8702** [comment]
现在似乎没问题？

**Comment by Guanchishan** [comment]
似乎很顺利。
