### ISSUE TITLE
结构化以后文本不见了

### ISSUE THREAD

**Issue by DDFShanyu** [MindongLab/yngdieng#181]
**问题描述**
文本消失了一段，如“单单”条目

**如何重现**
打开“单单”条目就可以看到了

**预期表现**
正常出现文本

**截图**
如有可能，请提供截图。

**电脑 (如果是，请填写):**
 - 操作系统: [如 Windows]
 - 浏览器: [如 chrome, safari]
 - 浏览器版本: [如 22]

**你所用的手机 (如果是，请填写):**
 - 品牌和型号: [如 iPhone6]
 - 操作系统: [如 iOS8.1]
 - 浏览器: [如 内置浏览器，UC 浏览器]
 - 浏览器版本: [如 22]

**其他信息**
其他任何你觉得有助于解决问题的信息。

**Comment by ztl8702** [comment]
<img width="572" alt="Screen Shot 2020-04-11 at 1 36 42 pm" src="https://user-images.githubusercontent.com/2714446/79036291-7cdaab00-7bf9-11ea-9425-aae2cf7669cc.png">

“单单”条目目前正常，你已经修改过了？

**Comment by DDFShanyu** [comment]
好像是



---原始邮件---
发件人: "Radium"<notifications@github.com&gt;
发送时间: 2020年4月11日(周六) 中午1:37
收件人: "MindongLab/yngdieng"<yngdieng@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ZySieng"<2056171287@qq.com&gt;;
主题: Re: [MindongLab/yngdieng] 结构化以后文本不见了 (#181)




 

 
“单单”条目目前正常，你已经修改过了？
