### ISSUE TITLE
 #註= 解析错误

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#182]
**词条网址**

http://yngdieng-staging.mindong.asia/feng/p182_2

**错误之处**

**应更正为**

**Comment by Guanchishan** [comment]
![image](https://user-images.githubusercontent.com/30859354/78991587-d72d2a80-7b6b-11ea-8097-7d423f339b82.png)
显示逻辑y有待优化

**Comment by ztl8702** [comment]
https://yngdieng-staging.mindong.asia/feng/p72_28 已修复.
<img width="462" alt="Screen Shot 2020-04-11 at 7 45 09 pm" src="https://user-images.githubusercontent.com/2714446/79042764-f50e9400-7c2c-11ea-8ac4-607b629f10c6.png">
