### ISSUE TITLE
蔓菁骹其注释

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/yngdieng#189]
**词条网址**

http://yngdieng-staging.mindong.asia/feng/p287_15

**错误之处**
![image](https://user-images.githubusercontent.com/30859354/79012206-59334880-7b98-11ea-9c14-0f8a82fb6ede.png)

**应更正为**
雞爪

**Comment by ztl8702** [comment]
这个你直接帮我改一下？

**Comment by Guanchishan** [comment]
現時亦是透過zeu修改？

**Comment by ztl8702** [comment]
没有，就是直接改feng.txt

**Comment by Guanchishan** [comment]
也就是说，现在不需要动用zeu工具了吗？这样倒是简单多了。我去修改。

Radium <notifications@github.com> 于2020年4月11日周六 下午6:34写道：

**Comment by ztl8702** [comment]
> 也就是说，现在不需要动用zeu工具了吗？

改 feng.txt， zeu 不是必须的。但是改完可以运行 `zeu precheck` 检查榕拼和解释格式是否有问题。(不运行也可以，改的量小，如果出问题了其他人看到会帮你改正）

**Comment by Guanchishan** [comment]
已校对原书，的确有误。已修改，兹关闭。
