### ISSUE TITLE
条目录音提交和审核流程

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#204]
**你提出的功能想解决什么问题**

单字音的合成语音上线还需要一段时间。而连读音合成难度较大，也不是短时间内可以达到理想效果的。最理想读音的其实还是真人语音。因此考虑让网友提交读音，但是需要人工审核。

**你觉得理想的解决方案是什么**

* 榕典界面上提供一个“贡献语音”按钮；直接在网页上录音。
* 需要一个审核语音的后台界面。管理员可看到待审核的语音，试听，审核。若一个条目，有多个语音都通过审核，管理员可以为选择一个“最优”作为默认（点击“连读音”的时候播放），剩余的语音可显示在条目正文下方或隐藏。

**其他可能的解决方案**
你考虑过的，能解决同样问题的其他可能方案。

* 连读音 TTS ，理论上可实现，但执行起来肯定会有很多细节，不易做得“真”。可同步进行。
* 统一、分配请播音员、闽语演员等来录音。可同步进行。

**其他信息**

初步仅收集福州市区音。若行之有效，此系统可拓展成收集各地语音。

**Comment by ztl8702** [comment]
TODOs:

[ ] 设计提交语音 UI
[ ] 设计审核流程和 UI 方案

**Comment by Guanchishan** [comment]
> 初步仅收集福州市区音

与其控制为福州市区音，不如一开始就广纳各闽东语读音？并允许上传者选择自己的区域（如仓山），填写自己的小区域（如黄山）。然后在后台审核上优先审核需要赶紧使用的“标准市区音”？

**Comment by ztl8702** [comment]
Good point

**Comment by Guanchishan** [comment]
2020-08-15榕典/输入法例会上讨论认为，用户提交录音需要信息如下：

- 收集信息：性别/地方
- 收集信息时机：注册时填写

---

我们是否需要用户录音时的年龄？

如果用户注册时不填写出自何地，是否在每次上传时留下一个小选框鼓励用户把地址填了？

**Comment by Guanchishan** [comment]
界面设计稿@2020-08-17
![image](https://user-images.githubusercontent.com/30859354/90687900-2b75b300-e2a0-11ea-9428-4b36ab25f1d0.png)
图里有设计一个小磁贴纪念林圜先生。别的磁贴是点赞，林先生这个就改成点蜡，如图。
或许可以满足[对林先生特别致谢](https://github.com/MindongLab/yngdieng/issues/272#issuecomment-657645795)的需求。
