### ISSUE TITLE
分开不同来源注释

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/yngdieng#211]
**你提出的功能想解决什么问题**
目前网友加注（主要好像是子善和叶修齐同学在做）和原书注释似乎是混起来的？参考[zy](http://yngdieng-staging.mindong.asia/feng/p45_27)条目：
![image](https://user-images.githubusercontent.com/30859354/79115716-2916c000-7db9-11ea-89f1-965c08d794ba.png)

**你觉得理想的解决方案是什么**
似乎可以考虑分开？如在样式设计上能体现出“原书注”“榕典注”？
考虑到feng.txt中二者一个是写作管道符号，一个是井号加注字，分开没有数据上的难度。

**其他可能的解决方案**
当然是否需要分开可以再做讨论。个人建议分开。

**其他信息**

**Comment by ztl8702** [comment]
Fixed in #336
