### ISSUE TITLE
搜索结果页会见到条目的斜杠

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/yngdieng#215]
**问题描述**
简要描述出了什么问题
![image](https://user-images.githubusercontent.com/30859354/79343927-a9782500-7f61-11ea-89d9-d5d4944ec125.png)

当然进入正文后就没了
![image](https://user-images.githubusercontent.com/30859354/79344099-ee03c080-7f61-11ea-9586-8794caed2b5c.png)

**如何重现**

随便搜个会含有出处的例句，在表示出处的文字后面应该都会有斜杠。

**预期表现**
你原本预期（假设没有这个bug）、正常的结果应该是什么？

不影响理解，但是有斜杠毕竟不美观。

**截图**
如有可能，请提供截图。

**你所用的手机 (如果是，请填写):**
 - 品牌和型号: 小米
 - 操作系统: 安卓
 - 浏览器: 谷歌

**其他信息**
其他任何你觉得有助于解决问题的信息。

**Comment by ztl8702** [comment]
这个在新的后端重构中会一并解决（因为搜索结果会重新实现）。不另行“打补丁”。

**Comment by Guanchishan** [comment]
既然以後解決，直接close。有需要隨時開起。
