### ISSUE TITLE
把ng识别成了非法音节

### ISSUE THREAD

**Issue by DDFShanyu** [MindongLab/yngdieng#218]
**问题描述**
如题

**如何重现**
   --> feng.txt: 行 6290
     |
6290 | 【伓是坯】 {ing242 sei242 pui55,ng242 sei242 pui55} ng21 ni55 pui55 ①指責人没有廉耻心，不要臉，猶如北京話的“不是 
東西”：許隻儂野～，汝講{什乇,世乇}伊都無聽{嘴,喙}(指無籌如何都不聽勸)，汝莫睬伊②指小孩不聽話，調皮搗蛋：許隻{兒囝,伲囝} 
哥(那孩子){真,盡}～，拍(打)死{??,儥}(不會)變|汝給我坐定，莫～|～其(的)，給我死轉去(回家)
     |                                                     ^^^^

                                                                                             ng21 不是符合规范的榕拼音节
.

**预期表现**
你原本预期（假设没有这个bug）、正常的结果应该是什么？

**截图**
如有可能，请提供截图。

**电脑 (如果是，请填写):**
 - 操作系统: [如 Windows]
 - 浏览器: [如 chrome, safari]
 - 浏览器版本: [如 22]

**你所用的手机 (如果是，请填写):**
 - 品牌和型号: [如 iPhone6]
 - 操作系统: [如 iOS8.1]
 - 浏览器: [如 内置浏览器，UC 浏览器]
 - 浏览器版本: [如 22]

**其他信息**
其他任何你觉得有助于解决问题的信息。

**Comment by ztl8702** [comment]
可添加例外， 榕拼规范要更新一下

**Comment by DDFShanyu** [comment]
0.4.0就更新了&nbsp;


子善（中国账号）
zysieng@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Radium"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 凌晨4:30
收件人: "MindongLab/yngdieng"<yngdieng@noreply.github.com&gt;; 
抄送: "閩東子善"<2056171287@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MindongLab/yngdieng] 把ng识别成了非法音节 (#218)





 
可添加例外， 榕拼规范要更新一下

**Comment by ztl8702** [comment]
> 0.4.0就更新了

我在榕拼0.4.0-preview2主方案和福州方案里搜索了一下"ng"，没有看到有明确说明：
* ng 作为声母可以直接带声调
* ing 和 ng 使用上区别（强调和非强调）

**Comment by Guanchishan** [comment]
現在這個問題算解決了未

**Comment by ztl8702** [comment]
fixed in 4b8bbc3a10905022721d0adf545412baec63d941
