### ISSUE TITLE
LOGO歪

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#220]
![Screenshot_20200417-073225](https://user-images.githubusercontent.com/2714446/79516328-a07c7600-807d-11ea-9f29-837487274953.png)
**问题描述**
简要描述出了什么问题

**如何重现**

重现步骤：
1. 打开 任意词条页
2. 回到首页

**预期表现**
你原本预期（假设没有这个bug）、正常的结果应该是什么？

**截图**
如有可能，请提供截图。

**电脑 (如果是，请填写):**
 - 操作系统: [如 Windows]
 - 浏览器: [如 chrome, safari]
 - 浏览器版本: [如 22]

**你所用的手机 (如果是，请填写):**
 - 品牌和型号: [如 iPhone6]
 - 操作系统: [如 iOS8.1]
 - 浏览器: [如 内置浏览器，UC 浏览器]
 - 浏览器版本: [如 22]

**其他信息**
其他任何你觉得有助于解决问题的信息。

**Comment by Guanchishan** [comment]
我这边使用chrome于电脑，也发现LOGO会横向偏移，重现步骤一致。

**Comment by ztl8702** [comment]
This was due to CSS className conflict in

```
```

```
```
