### ISSUE TITLE
TTS （文本转语音）

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#272]
我们已经有福州话大多数音节的音频。只需要把词典数据中的发音（榕拼）转化成对应的音频文件。(我们用最原始的TTS实现方式--“拼接音频”)

https://shimo.im/docs/35c397ff76b647b1#anchor-6481

TODOs：
* 根据榕拼确定使用哪些音频片段 （partly done）
* UI 界面
*  caching

需要考虑的点：

* 是在服务端合成语音频，还是在客户端合成音频
* 音频片段之间的间隔时间 ，如何听起来更自然
* API （URL Format）的设计
* 如果词条带有“没有发音音频的音节(e.g. 连读声母)”，先不显示发音按钮
* 音频文件存放部署的问题（有几百MB，不适合放在git repo中；服务器部署也有一些问题）

**Comment by ztl8702** [comment]
UI Mocks

![Screen Shot 2020-05-30 at 11 53 21 pm](https://user-images.githubusercontent.com/2714446/83332989-e78e9580-a2d0-11ea-9241-8db92b930e21.png)

**Comment by ztl8702** [comment]
@Towerhint let me know if you need any help!

**Comment by ztl8702** [comment]
Note on storing the audio files in git:

We can just store the .mp3 files -- the .wav files can be generated with a script (with `ffmpeg`; can also write a Bazel target to wrap the script) so no need to keep both in git.

And then use [Git LFS](https://git-lfs.github.com/) as well.

**Comment by ztl8702** [comment]
Feel free to send out small PR's (it's actually a good practice to break up code changes into small chunks). No need to make everything work in one go.

**Comment by ztl8702** [comment]
我们可能需要一个可以调节的参数：音节之间的时间间隔；“单字音”需要间隔长一点，“连读音”间隔短一点。

**Comment by insualk** [comment]
> 我们可能需要一个可以调节的参数：音节之间的时间间隔；“单字音”需要间隔长一点，“连读音”间隔短一点。

我们目前的办法是在`private static byte[] TrimSilence(string[] inputList, int msReserved = 0)`用`msReserved`。不过这个秒数是同时给前后都留出空白，然后如果原音频不足这个微秒数的话只保留原样，不额外添加空白。

**Comment by ztl8702** [comment]
OK Sounds good. We can pass a URL parameter such as `http://api.yngdieng.org/tts/<some text>?msReserved=`

**Comment by ztl8702** [comment]
Remaining tasks:

- [ ] ios safari 播放有问题（应该是Audio API 的兼容性问题）
- [ ] 不支持发音的音节，服务端返回404；UI 上应该要显示一个提示(snackbar)
- [ ] 间隔问题（这个最好多拿几个例子来比较一下；子善觉得间隔太长，我觉得间隔太短）

**Comment by ztl8702** [comment]
http://yngdieng-dev.mindong.asia/feng/p31_13 -> 这个发成 gou lang 是有问题的（变韵转换出错）

**Comment by ztl8702** [comment]
@insualk do you want to handle these remaining tasks?

**Comment by insualk** [comment]
> @insualk do you want to handle these remaining tasks?

Sure.

**Comment by ztl8702** [comment]
cool. lmk if you need any help.

**Comment by ztl8702** [comment]
TODO： 整理几十个有代表性的词条。用于微调音频后的前后比较。可能选30-50个吧。

选词标准：
1. 是可以发出来的（没有音节缺失）
2. 具有一定的代表性（比如说涵盖了有变韵、无变韵的音节，涵盖了不同声调的组合）
3. 也可以是生造的音节 （“无意义词” / non-sense word）；我们可以生成任意音频（只要每个音节都是存在的）

@DDFShanyu

**Comment by ztl8702** [comment]
TODO: 

- [ ] 整理一个“缺失音节表”

**Comment by ztl8702** [comment]
另：我们讨论过的一个idea（可以同时做）：

* 做一个微信录音小程序，邀请我们认识的福州话发音人（闽语演员、播音员等等）来录制每个词的真人语音。分工一下，每天打开微信小程序录几十个词。

**Comment by insualk** [comment]
> Remaining tasks:
> 
> * [ ]  ios safari 播放有问题（应该是Audio API 的兼容性问题）
> * [ ]  不支持发音的音节，服务端返回404；UI 上应该要显示一个提示(snackbar)
> * [ ]  间隔问题（这个最好多拿几个例子来比较一下；子善觉得间隔太长，我觉得间隔太短）
> * [ ]  oo 发不出来，但是音频是存在的（这个应该是 YngpingTtsUtil 的转换问题） [EXAMPLE ](http://yngdieng-dev.mindong.asia/feng/p352_12)
> * [ ]  帮助页面加一下对音库提供人 ”福老爷“ 林圜 先生 的感谢

`FinalAudioMapping`里的这两行：
```
{"01", new string[]{"ung", "oung"}},
...
{"20", new string[]{"oung", "aung"}},
```
是不是应该把`01`的松韵映射改成`ooung`？

**Comment by ztl8702** [comment]
>  是不是应该把01的松韵映射改成ooung？

01 是春韵 ung/oung 没错。

20 是要改 aung -> ooung.

**Comment by Guanchishan** [comment]
> * 帮助页面加一下对音库提供人 ”福老爷“ 林圜 先生 的感谢

参考[这个方案](https://github.com/MindongLab/yngdieng/issues/204#issuecomment-676686574)如何？

**Comment by Guanchishan** [comment]
發現一個問題，入聲連讀時產生-h55、-h33、-k55、-k33音調，會變得沒有聲音，但實際上可能可以用-k5、-h5來發音？

**Comment by ztl8702** [comment]
> 發現一個問題，入聲連讀時產生-h55、-h33、-k55、-k33音調，會變得沒有聲音，但實際上可能可以用-k5、-h5來發音？

这个应该要用舒声的55 33来发。同#698

**Comment by ztl8702** [comment]
Calling it done. Remaining tasks are nice-to-have.
