### ISSUE TITLE
在每个条目的右上角实现“异体字”

### ISSUE THREAD

**Issue by DDFShanyu** [MindongLab/yngdieng#306]
**你提出的功能想解决什么问题**

**你觉得理想的解决方案是什么**
目前在zingzeu_words里已经有了
A=X,X,X
来表示异体字
未来可在榕典右上角显示这些异体字
先决条件是mapping中的id全部匹配

**其他可能的解决方案**
你考虑过的，能解决同样问题的其他可能方案。

**其他信息**

**Comment by ztl8702** [comment]
同 #426
