### ISSUE TITLE
显示同音替代字

### ISSUE THREAD

**Issue by DDFShanyu** [MindongLab/yngdieng#307]
**你提出的功能想解决什么问题**
在榕典条目中显示同音替代字
目前的“榕典-冯书-李书用字对照表”，只是说明了榕典本身的用字偏好，
但冯书中的同音替代字，feng.txt中没有表示

**你觉得理想的解决方案是什么**
可在汉字后添加“*”号来标记前字是同音替代字

**其他可能的解决方案**
你考虑过的，能解决同样问题的其他可能方案。

**其他信息**

**Comment by ztl8702** [comment]
#328
