### ISSUE TITLE
显示原书用字

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#340]

**Comment by ztl8702** [comment]
* 显示原书时， 冯书连读音隐藏

**Comment by ztl8702** [comment]
- [ ] TODO： 榕拼转冯书IPA的规则 @DDFShanyu

**Comment by DDFShanyu** [comment]
最近随着我们的来源增多（戚林、李书、dfd等），我对于显示原书这个功能有了更系统的设想，之前也没有完整地在github说过，就在这里说了。

**Comment by DDFShanyu** [comment]
最近随着我们的来源增多（戚林、李书、dfd等），我对于显示原书这个功能有了更系统的设想，之前也没有完整地在github说过，就在这里说了。之前我们在KFC聊过一个显示原书的构想，那个我认为可以作废了。

### 总体设想：
**条目最上方的大字**，显示的是——推荐用字和榕拼
**每个来源的条目**，显示的是——原书用字和原书拼音
**每个来源的例句**，显示的是——推荐用字和榕拼
提供将“每个来源的例句”的用字从“推荐用字和榕拼”切换回“原书用字和原书拼音”的功能

### 图例：
不会传图，研究一下

### 理据：
榕典总的来说是一部多来源的线上词典，统一用字和拼音也是为了方便搜索和查看，不是说就这么把原书内容给改掉了。
随着来源的增多，原来修改的方式已经不能够持续——原来的方法是我用{,}去改feng、li里面的数据。但是有了戚林、dfd、甚至是各地地方志之后，这种方法就没有用了。比如说houng1这个音，戚林写的是“烟”字，榕典推荐用字是“熏”，难不成还得把戚林八音改了？
加之，也有一些依伯依姆议论我们乱改原书，从实用的角度来看，的确可以忽略这些声音，但是也不能放着这些言论不管，反例可以看闽江学院的字典，现在名声基本已经臭掉了，我们得防止这种事情发生在榕典身上。
因此，不能再这么改下去了，要作出改变，但是为了方便查询检索，统一用字和榕拼也不能舍弃。折衷的方法是，以推荐用字和榕拼为主，提供显示原书的功能。

用户搜出来的条目，**条目最上方的大字**，肯定是显示推荐用字和榕拼。
**每个来源的条目**，显示原书的用字和拼音——目前的榕典这里显示的依然是推荐用字，得改掉——因为像戚林八音这样的来源，我们不可能把他的用字给改掉。
为了方便用户查阅例句，我们将**每个来源里面的用字**默认显示为推荐用字，这里可以切换为原书用字，显示为条目旁白的一个**小按钮**。

### 方法：
技术不太了解，满讲的
以zingzeuID为纲，每个来源的条目都与ID作映射。
**条目最上方的大字**，直接显示zingzeuwords里面的用字和拼音
**每个来源的条目**，汉字显示的是feng、li里面{,}的逗号前的汉字，拼音则根据转化规则统一由榕拼转化而成
**每个来源的例句**，汉字显示的是feng、li里面{,}的逗号后的汉字，切换后，显示逗号前的

### 预先要解决的事情：
处理技术环节以外，有两件事情要紧
要将zingzeuID进行映射，譬如戚林，这个要早做
zingzeuwords内的用字和拼音，要和目前feng{,}修改后的保持一致。之前我们尝试过以zingzeuwords为纲来进行搜索，但是因为输入法词库有若干问题而废止了，现在要系统地检查一遍输入法的词库。我的看法是，先做冯版，看看输入法的用字、拼音能不能和修改后的冯版合得上，做一个系统性的筛查，不匹配的人工筛选出来。
