### ISSUE TITLE
结构化bug：“蜀”字条目的注释显示不完全

### ISSUE THREAD

**Issue by DDFShanyu** [MindongLab/yngdieng#342]
**问题描述**
原文
“蜀{soh}”和“一eik24”的用法不完全相同。讀數目字一至十時，“蜀”後面是“兩”；“一”後面是“二”。小數和分數只用“一”不用“蜀”\：一點二|三點一|三分一。序敷也只用“一”\：第一|△一官大娘高廳坐，二子攜孫來拜年|△一拍厝房門喜連連…二拍厝門手無(不)停。在一般最詞和度量衡單位前用“蜀”不用“一”\：蜀日|蜀隻|蜀條|蜀斤|蜀錢|蜀里|蜀鋪路。在多位數中，個位可用“蜀”，也可用“一”\：一百零一|一百零蜀。此時的“蜀”要讀（suoh5）。百、千、萬、億等前面用“蜀”不用“一”\：蜀百|蜀千|蜀萬|蜀萬蜀千蜀百零(多)。十、百、千、萬後面的數目用“一”，不用“蜀”\：十一|百一(一百一十)|千一(一千一百)|萬一(一萬一千)。另見suoh5
只显示到了
“蜀{soh}”和“一eik24”的用法不完全相同。讀數目字一至十時，“蜀”後面是“兩”；“一”後面是“二”。小數和分數只用“一”不用“蜀”\：一點二
就是说
“|”以后的没有显示

**如何重现**
http://www.yngdieng.org/feng/p413_13
http://www.yngdieng.org/feng/p419_15 

**预期表现**
你原本预期（假设没有这个bug）、正常的结果应该是什么？

**截图**
如有可能，请提供截图。

**电脑 (如果是，请填写):**
 - 操作系统: [如 Windows]
 - 浏览器: [如 chrome, safari]
 - 浏览器版本: [如 22]

**你所用的手机 (如果是，请填写):**
 - 品牌和型号: [如 iPhone6]
 - 操作系统: [如 iOS8.1]
 - 浏览器: [如 内置浏览器，UC 浏览器]
 - 浏览器版本: [如 22]

**其他信息**
其他任何你觉得有助于解决问题的信息。

**Comment by ztl8702** [comment]
这是因为目前”注“里面的内容不支持结构化

**Comment by ztl8702** [comment]
临时解决方法：

把词条目"注" 里面的所有 `|` 替换成 `\|`

**Comment by ztl8702** [comment]
这种 注 带例句的情况多不多？

**Comment by DDFShanyu** [comment]
这个工程量会不会太大了，有1500个‖
主要是怎么从找出‖后面的|，我不会
&nbsp;


子善（中国账号）
zysieng@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Radium"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 晚上9:50
收件人: "MindongLab/yngdieng"<yngdieng@noreply.github.com&gt;; 
抄送: "閩東子善"<2056171287@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MindongLab/yngdieng] 结构化bug：“蜀”字条目的注释显示不完全 (#342)





 
这种 注 带例句的情况多不多？

**Comment by ztl8702** [comment]
用以下正则：

```
‖.*\|.*
```

只有13个

**Comment by ztl8702** [comment]
DDFShanyu 已手动修复

**Comment by DDFShanyu** [comment]
响亮你好，这是帮助页面的新文本，麻烦你在github上更新了，直接覆盖原来的帮助页面，并处理一下排版即可。


https://shimo.im/docs/yW6HRkq8TVX3JXrW/ 《榕典帮助（2020.8.13版）》，可复制链接后用石墨文档 App 或小程序打开


起动
