### ISSUE TITLE
历时音韵中的“反切”用词不当

### ISSUE THREAD

**Issue by DDFShanyu** [MindongLab/yngdieng#370]
**问题描述**
![image](https://user-images.githubusercontent.com/32233404/85836743-a99a6980-b7c9-11ea-8c5d-89ed37705139.png)
这个东东不是“反切”，是八音的“音韵地位”

**如何重现**
http://www.yngdieng.org/feng/p165_14
如本条目

**预期表现**
你原本预期（假设没有这个bug）、正常的结果应该是什么？

**截图**
如有可能，请提供截图。

**电脑 (如果是，请填写):**
 - 操作系统: [如 Windows]
 - 浏览器: [如 chrome, safari]
 - 浏览器版本: [如 22]

**你所用的手机 (如果是，请填写):**
 - 品牌和型号: [如 iPhone6]
 - 操作系统: [如 iOS8.1]
 - 浏览器: [如 内置浏览器，UC 浏览器]
 - 浏览器版本: [如 22]

**其他信息**
其他任何你觉得有助于解决问题的信息。

**Comment by DDFShanyu** [comment]
*历史音韵

**Comment by insualk** [comment]
意思是说把「反切」二字改为「历史音韵」吗？

**Comment by DDFShanyu** [comment]
对



---原始邮件---
发件人: "Aliang"<notifications@github.com&gt;
发送时间: 2020年6月27日(周六) 凌晨2:32
收件人: "MindongLab/yngdieng"<yngdieng@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ZySieng"<2056171287@qq.com&gt;;
主题: Re: [MindongLab/yngdieng] 历时音韵中的“反切”用词不当 (#370)




 
意思是说把「反切」二字改为「历史音韵」吗？

**Comment by DDFShanyu** [comment]
不是，刚刚打错了。
是把反切改成「音韵地位」



---原始邮件---
发件人: "Aliang"<notifications@github.com&gt;
发送时间: 2020年6月27日(周六) 凌晨2:32
收件人: "MindongLab/yngdieng"<yngdieng@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ZySieng"<2056171287@qq.com&gt;;
主题: Re: [MindongLab/yngdieng] 历时音韵中的“反切”用词不当 (#370)




 
意思是说把「反切」二字改为「历史音韵」吗？

**Comment by ztl8702** [comment]
出于好奇，你能不能解释一下“反切”和“音韵地位”的区别？

**Comment by ztl8702** [comment]
Fixed in #375

**Comment by DDFShanyu** [comment]
反切是这样的 
郑，之邓切
天，提烟切
镭，勒雷切
音韵地位是这样的
郑，澄梗三开去劲敬
郑，低山下去
郑，照母 庚青韻 去聲 正小韻

**Comment by ztl8702** [comment]
所以反切一定是指现代音？
