### ISSUE TITLE
微信小程序

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#442]
### 任务拆分
 - [x]  项目初始化
 - [x] CI 搭建 
 - [ ] 更新 Figma 内的界面图 -> @ztl8702 
 - [x]  界面搭建
 - [x] Set up grpc-gateway (GRPC 转 REST）-> @ztl8702
 - [x]  接入数据
 - [ ] Bazel 化
### 框架选择
 - Taro@3
 - react
 - sass
 - redux

**Comment by ztl8702** [comment]
@rovinglight 你来补充一下细节/任务吧

**Comment by ztl8702** [comment]
（我自作主张update了一下任务列表）

**Comment by Guanchishan** [comment]
目前进展如何？

**Comment by ztl8702** [comment]
微信小程序功能基本都解决了吧 （现在反而是网页版滞后）

**Comment by Guanchishan** [comment]
对 因为我没看懂主楼的bazel化是什么意思。
如果差不多都解决了，这个issue关闭？

**Comment by ztl8702** [comment]
> 我没看懂主楼的bazel化是什么意思。

[bazel](https://bazel.build/) 是网页端用的依赖管理和建构系统。“bazel化”是说统一小程序和网页端的依赖。这个纯粹是技术细节。也不需要现在做。
