### ISSUE TITLE
蔣做 

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#472]
**词条网址**

http://www.yngdieng.org/feng/p316_1

**错误之处**
市区连读 zuong24 njoo213 

**应更正为**

zuong55

**Comment by DDFShanyu** [comment]
这个开会时候就已经改好了，可以close掉



---原始邮件---
发件人: "Radium"<notifications@github.com&gt;
发送时间: 2020年8月2日(周日) 晚上10:15
收件人: "MindongLab/yngdieng"<yngdieng@noreply.github.com&gt;;
抄送: "Assign"<assign@noreply.github.com&gt;;"ZySieng"<2056171287@qq.com&gt;;
主题: [MindongLab/yngdieng] 蔣做  (#472)




 
词条网址
 
http://www.yngdieng.org/feng/p316_1
 
错误之处
 市区连读 zuong24 njoo213
 
应更正为
 
zuong55
