### ISSUE TITLE
clang-format 处理不了tsx和scss文件

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#520]
clang-format 处理不了tsx和scss文件。是不是可以考虑除了.ts .js以外的文件，都交给 prettier 来格式化。

**Comment by ztl8702** [comment]
@rovinglight  clang-format 和 prettier 有发生冲突吗？（比如说 prettier 格式化之后 clang-format 又“不满意”）

**Comment by ztl8702** [comment]
ts 应该和 tsx 用同一个格式化工具吧。 （都用 prettier）  clang-format仅留给C#代码用。

**Comment by rovinglight** [comment]
> @rovinglight clang-format 和 prettier 有发生冲突吗？（比如说 prettier 格式化之后 clang-format 又“不满意”）

这情况是有的，两个工具格式化出来的代码风格差很多。js 这部分是可以交给 prettier 来处理。

**Comment by ztl8702** [comment]
可以的。prettier你来配置一下？

**Comment by rovinglight** [comment]
OK

**Comment by ztl8702** [comment]
Fixed in #563
