### ISSUE TITLE
TTS的u21音放成了ou242

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/yngdieng#521]
**问题描述**
看起来现在给连读的21音安排了213的读音进去。非常机智，不过有个问题：

http://yngdieng-dev.mindong.asia/feng/p39_13

有敆食的u21 gak5 sieh5，音频放成了ou242 gak5 sieh5。

**预期表现**
你原本预期（假设没有这个bug）、正常的结果应该是什么？

有没办法搞个低低的u21，搞不了就索性不放，不返回播放按钮

**Comment by Guanchishan** [comment]
停锣煞鼓这个词有点纠结：http://yngdieng-dev.mindong.asia/feng/p219_15 不敢肯定用deing213当作ding21合不合适。

**Comment by Guanchishan** [comment]
ztl：这个是bug 松紧混了
![image](https://user-images.githubusercontent.com/30859354/90658358-12f0a300-e276-11ea-9c6e-7ac3d6203f85.png)

**Comment by ztl8702** [comment]
@insualk  have you started on this? If not I can take it next week.

**Comment by ztl8702** [comment]
这个涉及到发音正确性的问题，应该是要优先解决的。

**Comment by Guanchishan** [comment]
嗯，这件事在用户交流群也被指摘了。辛苦解决下咯。

发自我的iPhone

**Comment by insualk** [comment]
> 这个我想解决方案是首先要修改一下
> 
> https://github.com/MindongLab/yngdieng/blob/95f69139d4ba92ed0bf0b2db89683226cda99e2f/server/backend/TextToSpeech/YngpingTtsUtil.cs
> 
> 的逻辑：
> 
> 目前的逻辑是，把输入的榕拼，进行分解，找出对应的声母、韵母、声调编号；然后再组合成音频文件名。这样写的逻辑有点反直觉，不好维护和修改。
> 
> 应该改成这样：
> 
> * 先完整地生成每个音频文件对应的榕拼，比如 010101-> bung55, 010102 -> bung33, etc
> * 然后对每一个输入的榕拼，看是否有直接匹配的，如果没有，则进行一系列fallback（比如说 21 改成 213 看看有没有匹配; h/k 换一换 ；nj再改成n ，etc;直到找到一个近似匹配的，或者找不到为止）

问题是不是出在03对应了21和213，但是213变韵而21不变？

**Comment by ztl8702** [comment]
> 03对应了21和213，但是213变韵而21不变？

正确

**Comment by ztl8702** [comment]
The fix is live.

https://staging.ydict.net/feng/p39_13

**Comment by ztl8702** [comment]
Thanks @insualk
