### ISSUE TITLE
建议导航栏上搜索框能固定住

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/yngdieng#522]
**你提出的功能想解决什么问题**
目前在词条详情页顶部栏没有搜索框，用户想搜还要返回；而莆仙词典词典的详情页有搜索框

**你觉得理想的解决方案是什么**
导航栏上搜索框能固定住

![image](https://user-images.githubusercontent.com/30859354/90674609-ed6e9400-e28b-11ea-8626-bcd7a2b3cfdd.png)

建议by子善

**Comment by ztl8702** [comment]
Dup of #527
