### ISSUE TITLE
字音与词音的注音方式要统一

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/yngdieng#524]
**问题描述**
字音与词音的注音方式没要统一
目前字音各用一套，如八字bek4/baik24

**如何重现**
随便找个汉字去搜就会发现
![image](https://user-images.githubusercontent.com/30859354/90675239-c6fd2880-e28c-11ea-9cbd-aacabc0bd763.png)
![image](https://user-images.githubusercontent.com/30859354/90675269-ce243680-e28c-11ea-9bbd-27071d4e6233.png)
声调用的不是一个标记系统

**预期表现**

优先显示今读，这个数字编号的八音最好找个角落塞住，不然会引起混淆

**Comment by ztl8702** [comment]
这个在搜索V2已解决。
