### ISSUE TITLE
龙船词表（homeland合作demo）

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#557]
TODOs:

- [x] 扫码打开小程序指定页面 (某个 route？ )
- [x] 词条页（单个词条页面） UI
- [x] 词条页 逻辑 （加载指定的条目）
   - [x] 可以直接把数据hardcode在 js 代码里
- [x] 词表页面 UI
- [x] 音频加载和播放功能
   - [x] <del>要去把音频传到服务器/OSS上</del>

**Comment by Guanchishan** [comment]
音频传哪？

**Comment by Guanchishan** [comment]
update：homeland拜三要词表。我们尽量拜三出demo，不行则周末。

**Comment by ztl8702** [comment]
> 音频传哪？ 

发给我（之前email给的我是最新的吗？）

**Comment by Guanchishan** [comment]
【故事】标签的效果图（已发送给做微信小程序的朋友看）：
![鱼梁 故事](https://user-images.githubusercontent.com/30859354/91186330-820c4280-e721-11ea-853c-5ab08a569858.png)
![枙 故事](https://user-images.githubusercontent.com/30859354/91186343-83d60600-e721-11ea-8ebb-13862fe49dd5.png)

其中鱼梁是本文花篇幅去介绍了，所以灰色文字写的是【讲述】，枙只是给提到了，所以是【提及】

**Comment by Guanchishan** [comment]
> > 音频传哪？ 
> 
> 
> 
> 发给我（之前email给的我是最新的吗？）

最新音頻在小程序製作手上，其編號殊異，內容有較大補充。

**Comment by Guanchishan** [comment]
> update：homeland拜三要词表。我们尽量拜三出demo，不行则周末。

開發表示：拜三來不及，還是做好點，週末吧

**Comment by ztl8702** [comment]
Thanks for the update

**Comment by rovinglight** [comment]
抱歉，得拖一下到今晚，差不多能把 TODOs 完成。

**Comment by ztl8702** [comment]
no problem

________________________________

**Comment by rovinglight** [comment]
关于扫二维码的功能，之前是说通过「扫描普通二维码的方式」来实现。现在看来可以不必如此，既然小程序码能附带路径，直接生成小程序码就行。

**Comment by ztl8702** [comment]
> 既然小程序码能附带路径，

确定吗？我之前只是试过体验版的二维码可以附带路径。未试过那种圆形的小程序码可不可以。

**Comment by rovinglight** [comment]
> 确定吗？我之前只是试过体验版的二维码可以附带路径。未试过那种圆形的小程序码可不可以。

是可以的，我们之前是有提到过一个[获取小程序码的接口](https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/qr-code/wxacode.getUnlimited.html)能做到，但需要小程序发布。既然有打算发布的话，就可以先发布后生成一下小程序码（赶时间的话也可直接发布一版，生成小程序码）。毕竟小程序码的观感要更好些。

解析的逻辑倒是可以提前做进去，在开发者工具是可以进行测试的。

**Comment by ztl8702** [comment]
先发布吧

**Comment by ztl8702** [comment]
回头想想，为了避免可能的风险（比如说假设小程序被禁），还是用正常的URL二维码比较好？

而且最好是我们自己控制的域名（自己跑一个短网址重定向服务在 go.ydict.net/），重定向到小程序。（这个可以做到重定向后自动打开小程序吗？）

这样给我们足够的灵活度 — 可以把它重定向到不同的网址（比如一个landing page）或不同的小程序。

**Comment by ztl8702** [comment]
看起来基本结案了？

**Comment by Guanchishan** [comment]
沒有什麼需要在這裡討論的了，close先？

**Comment by ztl8702** [comment]
👌 再次感谢 @rovinglight 大力实施💪🏻
