### ISSUE TITLE
Safari 播放 WAV 的问题

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#558]

**Comment by ztl8702** [comment]
Any updates?

**Comment by insualk** [comment]
可能相关：[无法导入第三方代码库](https://github.com/goldfire/howler.js/issues/688)

**Comment by ztl8702** [comment]
那个issue没有说bazel的问题吧

**Comment by insualk** [comment]
> 那个issue没有说bazel的问题吧

是在作者closed issue之后的那条评论里有人提到。

**Comment by ztl8702** [comment]
@insaulk did you see any errors in the browser console, after importing howler?

**Comment by ztl8702** [comment]
Any updates? Need help?

**Comment by insualk** [comment]
Yes. Can we schedule a one-to-one meeting?

**Comment by ztl8702** [comment]
dyk dyk

**Comment by ztl8702** [comment]
You can push a WIP branch and let me handle the rest. I am really fine with that.

**Comment by ztl8702** [comment]
<img width="158" alt="Screen Shot 2020-10-01 at 3 02 28 am" src="https://user-images.githubusercontent.com/2714446/94728311-a0093a80-0392-11eb-9b5a-1903f89784c0.png">

audio codec in Safari (as detected by Howler)
