### ISSUE TITLE
声调不确定 用什么表示

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#602]
用户可能不了解 花括号`{}`的用法 (其实我也不了解)

花括号不是榕拼的一部分，只是输入法词库技术需要（？）
 
![Screen Shot 2020-09-07 at 5 25 56 pm](https://user-images.githubusercontent.com/2714446/92372280-46b14100-f12f-11ea-9376-5225135a5445.png)

这里表示的意思是“hi 声调不定，具体声调要看后面跟了什么字”

那不如就显示成  `hi (声调可变)` 。用户点击 `声调可变` 这几个字，弹出一个解释。

**Comment by ztl8702** [comment]
示意图：

![Screen Shot 2020-09-07 at 5 29 33 pm](https://user-images.githubusercontent.com/2714446/92372558-b32c4000-f12f-11ea-8053-9df84baefb14.png)

**Comment by ztl8702** [comment]
@DDFShanyu @Guanchishan

**Comment by DDFShanyu** [comment]
{hi}



---原始邮件---
发件人: "Radium"<notifications@github.com&gt;
发送时间: 2020年9月7日(周一) 下午5:30
收件人: "MindongLab/yngdieng"<yngdieng@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"ZySieng"<2056171287@qq.com&gt;;
主题: Re: [MindongLab/yngdieng] 声调不确定 用什么表示 (#602)




 
示意图：

**Comment by Guanchishan** [comment]
用花括號吧。
能用聲調0嗎

**Comment by ztl8702** [comment]
我意思是我们内部数据用 花括号，面向公众则不再新增一个符号。面向公众：不标调 + UI上另行说明这个字声调依语境而定.

**Comment by ztl8702** [comment]
子善要打开issue看一下图片

**Comment by DDFShanyu** [comment]
不能用0



---原始邮件---
发件人: "Davidzdh"<notifications@github.com&gt;
发送时间: 2020年9月7日(周一) 晚上6:27
收件人: "MindongLab/yngdieng"<yngdieng@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"ZySieng"<2056171287@qq.com&gt;;
主题: Re: [MindongLab/yngdieng] 声调不确定 用什么表示 (#602)




 
用花括號吧。
 能用聲調0嗎

**Comment by DDFShanyu** [comment]
我建议还是用{}，或者标记（连读中）
因为这个{}不仅标记的是变调的，还表记变韵的

**Comment by DDFShanyu** [comment]
榕拼0.5会记录这个{}号

**Comment by ztl8702** [comment]
也行吧。既然韵会变的话（也就是基本上整个音节），用特殊调号或者0都不合适（回
@Guanchishan：0表示的轻声调和可变声调还是不同的）。我只是觉得 花括号长得很难看，但目前也没有更好的符号。

**Comment by ztl8702** [comment]
暂无行动事项（继续使用 `{}`）。关闭issue。
