### ISSUE TITLE
榕典新数据模型

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#692]
近期要设计一下。
先开个issue记录问题。

**Comment by ztl8702** [comment]
## 读音类型的问题

zingzeu_words 中设想的 SC（读音类型）包括 ：连读音、本字音两种。

* 地名读音往往不适用于“连读音/本字音”这样简单划分
   * @Guanchishan  地名一定名从主人，就好像普通话里也把六安这个地名读成lu而非liu一样。他die-la这个地名基本还是遵守福州市区的音调体系的

**Comment by ztl8702** [comment]
## 不同口音的处理

* 是“音频本位”：音频拥有对应的读音。还是：词条拥有读音，读音拥有音频？
#560

**Comment by Guanchishan** [comment]
## 同义词、近义词

目前是在contrib里面开了个同义词字段记录同义词。但是这会担心由于人工维护导致数据不一致的问题。
应该中心化管理同义词信息。用一个意义素统领诸多同义词。可能要另外开张表来记录这些信息。

**Comment by Guanchishan** [comment]
## 待遇表現
日语词。中文不知道怎么叫。意思是在社交活动所涉及的语言主体（说话人，写作者）与对方、话题人物三者之间的上下、亲疏等人际关系，以及这些关系在语言中的反映。体现在福州话里，就好像我们不敢在长辈面前说“講脬”“𡳞脬”一样，在吃宴席的时候不好说“食飽了”，只好说“食完了”，甚至听过福清牧师讲道说“今天”不说“今旦”。这也需要另外一张表单去按庄重程度线性排列（目前福州只想到庄重程度一个维度，怕搞太复杂；日语的话一般是坐标轴：横轴是庄重，纵轴是口语、书面）

**Comment by ztl8702** [comment]
## 何为条目，何为义项

zingzeu_words 目前理论上是给每个（字，音，义）组合 开一个ID。同字不同音-> 不同ID；同音不同义-> 不同ID（虽然说不同义。一般来说音也会不同？ e.g. 树兜）。但是每个ID又可能指向一个冯版条目、一个李版条目。冯、李对词义的划分，可能有所不同。

**Comment by ztl8702** [comment]
## 短语、熟语、歌谣、诗歌能不能加进来？

有的冯条目就是短语或熟语。未来也计划把几本熟语数据导入。熟语也用zingzeu ID？

**Comment by Guanchishan** [comment]
> 短语、熟语、歌谣、诗歌能不能加进来？
> 有的冯条目就是短语或熟语。未来也计划把几本熟语数据导入。熟语也用zingzeu ID？

不过在实践过程中，发现除了使用zingzeu ID的熟语本身，还需要两种ID：
一是**异文**。比如由于传唱、传抄等导致训读字本字混用、混说，以及衍文等问题，从而产生同一熟语的不同版本。（如[月光光照池塘](https://github.com/MindongLab/foochow-idioms-data/commit/fe47230abdceb38313f2ebe89c85f40793a900e1)。）这些不同版本本身肯定可以从属于不同zingzeuID，但是也要俾使从属于同一异文树下。
一是**同题**。比如真鸟囝不仅可以啄菠菠（三岁孩儿会唱歌那首），还能食番柿（飞机大炮着准备，解放台湾真容易），还能[抗病毒](https://mp.weixin.qq.com/s?__biz=MzA4MDIxMzU2OA==&mid=2660817388&idx=1&sn=37bfa0fe77eacd2b4c41f653b6bbf23d&chksm=84cbdac3b3bc53d57076404979af572bd9deb18820fc95dbbc7127d3ed26a543c7d84eea106b&token=662268260&lang=zh_CN#rd)，等等。很显然这么多真鸟囝，已经不只是异文的关系了，根本就是不同作品。但却属于同一个题目，可以设置一个“异文”之上的同题ID？

这些ID关系如下：
![image](https://user-images.githubusercontent.com/30859354/97547342-a5e15280-1a08-11eb-846c-ecb55f90ba3c.png)
