### ISSUE TITLE
TTS: pak21 pak33 tiu213

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#698]
https://staging.ydict.net/w/CgQ0NEY0

`pak21 pak33 tiu213` should be playable as `pa213 pa33 tiu213`

**Comment by ztl8702** [comment]
nguok33 -> nguo33

**Comment by insualk** [comment]
没有单个ng后不跟韵母的发音是吗？
如：ng242 sei242 pui55 伓是坯

**Comment by ztl8702** [comment]
> 没有单个ng后不跟韵母的发音是吗？
> 
> 如：ng242 sei242 pui55 伓是坯
> 
> 

ng242 可以用 ing242 近似替代

**Comment by Guanchishan** [comment]
ng沒聲音被榕典用戶群群友發現了XD

**Comment by ztl8702** [comment]
> ng沒聲音被榕典用戶群群友發現了XD

还有很多有待他们发现。

这个TTS音频目前能起的作用，一方面是给不会看汉字和榕拼的人，辨别搜索结果是否是自己想找的。所以不求完美。有总比没有好。

**Comment by ztl8702** [comment]
ng 这个没有音频啊。修的方式是要去模仿ling kuang的声音录一个。

**Comment by Guanchishan** [comment]
> ng 这个音节没有音频啊。修的方式是要去模仿ling kuang的声音录一个。

不是说打算用ing去替代？我觉得这是个很合理的方案啊

**Comment by Guanchishan** [comment]
ng连读时会有别的音调如ing21、ing53之类？ing53是有音频的吧

> ng242 可以用 ing242 近似替代 （虽然说ing242也没有音频）

**Comment by insualk** [comment]
> ng 这个音节没有音频啊。修的方式是要去模仿ling kuang的声音录一个。

我感觉单录ng七个音其实挺可行的。

**Comment by Guanchishan** [comment]
但是会怕和林圜先生的音不像？

**Comment by Guanchishan** [comment]
不介意不像的话，缺音都可以自行录制来补了。

**Comment by ztl8702** [comment]
pak21 pak33 tiu213 已解决。补录音频以后再说（或者谁有空可以录一下）

**Comment by Guanchishan** [comment]
补录是指ng的七个音吗 如不嫌弃我立刻就能录（但我嫌我福州腔不重，我想找个更有虾油腔的人录，但是这种建构出来，不存在于当今口语里的音节长辈不爱配合。天镭或者响亮有兴趣来吗）
