### ISSUE TITLE
小程序可分享页面

### ISSUE THREAD

**Issue by ztl8702** [MindongLab/yngdieng#699]
目前小程序内的页面都不可分享。（菜单中的分享按钮是禁用的）

应该至少要让这些页面可以分享：
* 首页
* 词条详情页
* 词表页
* 搜索结果页

**Comment by rovinglight** [comment]
分享之后生成的分享卡片有两个地方可以定制，标题和图片。他们的默认值分别是小程序名和当前页截图。  
- 截图部分：现在看起来效果都还行，暂时还没什么替换的必要。
- 标题部分：可以考虑定制一下，比如这样？看看有没有什么好建议。
  - 首页：榕典
  - 详情：【榕典】词条：XX
  - 词表：【榕典】词表：XX
  - 搜索：【榕典】搜索结果：XX

**Comment by ztl8702** [comment]
标题，网页版是这样：

首页： 榕典
详情： XX | 榕典
词表： 暂无
搜索： XX | 榕典
