### ISSUE TITLE
搜索bug：不能显示改变以后的用字

### ISSUE THREAD

**Issue by DDFShanyu** [MindongLab/yngdieng#721]
**问题描述**
不能显示推荐用字

**如何重现**
https://staging.ydict.net/search2/%E8%B9%B4
https://staging.ydict.net/search2/%E9%85%92%E6%BC%80
都是feng.txt里面{,}前的用字，而不是改变以后的

**预期表现**
就
酒倾

**Comment by ztl8702** [comment]
”就“是mapping的问题。

”酒倾“ 是zingzeu_words 用字未更新。

**Comment by ztl8702** [comment]
临时补丁：搜索索引优先使用feng汉字（如有feng，不显示zingzeu_words用字） 。明日生效。
