### ISSUE TITLE
记音字小圈圈

### ISSUE THREAD

**Issue by Guanchishan** [MindongLab/yngdieng#849]
也许可以用到的HTML代码：

`<span style="-webkit-text-emphasis: filled sesame;-ms-text-emphasis: filled dot;-moz-text-emphasis: filled dot;text-emphasis: filled dot;">のにおい</span>`

效果见此网页：https://guanchishan.github.io/posts/1408cdba.html

样式修改下，变成在汉字底部的空心圈圈就好了

**Comment by ztl8702** [comment]
Dup: https://github.com/MindongLab/yngdieng/issues/328
