### ISSUE TITLE
增加“词条关键词”

### ISSUE THREAD

**Issue by DDFShanyu** [MindongLab/yngdieng#88]
**你提出的功能想解决什么问题**
更快捷地查询普通话释义。
可以规定一个格式，添加在txt每行条目中间。
比如（满讲）：
【舒暢】	cy55 tuong213	cy53 luong213	①身體或精神上感到輕鬆愉快、舒服安逸：湯洗𡅏(洗了澡)，{真,盡}～|舒舒暢睏{一,蜀}眠|舒暢暢其(地)倒搖搖椅𡅏|舒舒暢暢洗{一,蜀}隻湯(洗個澡)②能使身體或精神上感到輕鬆愉快：賓館條件野好，野～	hint=爽,痛快
后面这个hint

**你觉得理想的解决方案是什么**
现有查询方式检索文本内普通话释义低效的问题。
上次有讨论过，比如说“舒畅”这个条目，原书释义只有“轻松愉快、舒服安逸”这八个字，若我想查找“开心”、“爽”、“痛快”等关键字，则查找不到这个词条。

**其他可能的解决方案**
你考虑过的，能解决同样问题的其他可能方案。
妹有。

**其他信息**
毛。

**Comment by DDFShanyu** [comment]
还有一个就是，注释的格式要再定义一下，
我原来写
#註=xxxxx
你看看怎么写比较好

**Comment by ztl8702** [comment]
这个可以写到 zingzeu_words 里面。

**Comment by Guanchishan** [comment]
如果我沒理解錯，這裡的hint與目前有自定詞彙表裏出現的「標籤」（tag）不是一個東西吧？贊成在自定義表裏增設hint字段。

**Comment by DDFShanyu** [comment]
> 如果我沒理解錯，這裡的hint與目前有自定詞彙表裏出現的「標籤」（tag）不是一個東西吧？贊成在自定義表裏增設hint字段。

不是，这个大抵是一种普通话翻译，方便检索用的。
contrib里面的tag我觉得意义不大反而，因为怎么去给词汇分类，没有统一标准，这样会导致分类很乱。

**Comment by Guanchishan** [comment]
> 因为怎么去给词汇分类，没有统一标准

那按照 #216 的讨论，以冯书为纲做套分类树就好了呗。

> 大抵是一种普通话翻译

确实hint值得比分类更优先

> contrib里面的tag我觉得意义不大

可能有一个意义，比如“公交报站”“福州地名”，我就可以拉出一批具备此性质的词，但我觉得这个意义日后可能可以发展为[单词表]( #20 )。

tag目前就当暂存区吧！

**Comment by Guanchishan** [comment]
我試𡅏敆 contrib 加添了 關鍵詞 字段。

ZySieng <notifications@github.com> 于2020年4月15日周三 上午10:43写道：

**Comment by Guanchishan** [comment]
@DDFShanyu 目前没在feng.txt见到关键词字段。尚未增设否？

**Comment by ztl8702** [comment]
feng.txt 不用加关键字。目标是加到 zingzeu_words 同 ID 的条目下。

**Comment by Guanchishan** [comment]
早实现了。关。
