### ISSUE TITLE
来源的Dictionary of Foochow Dialect表述不严谨

### ISSUE THREAD

**Issue by DDFShanyu** [MindongLab/yngdieng#969]
情况：
我们现在的数据不是DFD原书的，是附录的，只写Dictionary of Foochow Dialect会造成歧义
比如这里https://staging.ydict.net/feng/p68_1
这个“个”，DFD原书有两个音，ga和go。附录只有go一个音，ga漏写了，但是注释里面又记载了dfd有ga这个音，会让读者摸不着头脑。

解决办法：
这个数据是Index of Characters的，
英文的我不太明白怎么写（Dictionary of Foochow Dialect: Index of Characters吗？好像不太对）
中文可以写《榕腔注音辞典·目录》（原书把Index of Characters翻译成目录）

**Comment by ztl8702** [comment]
直接给DFD附录数据增加ga这个音？

**Comment by DDFShanyu** [comment]
不行，第一是，工作量太大了；第二是他原书附录就是这么写的

**Comment by DDFShanyu** [comment]
把来源名词给改了最省力

**Comment by ztl8702** [comment]
比起“是否注明Index of Character”的严谨性，我相信用户更在意的是能不能查到这个音。

实在要写的话，英文可以写 Index of Characters, DFD 或 DFD (Index of Characters) . 但我觉得对于大部分用户来说，这都是一个无关痛痒的细节

**Comment by DDFShanyu** [comment]
这本书Index of Character有很多问题，想要把所有问题都解决，还是得等到把DFD全书数位化以后才能系统性筛查。具体来源怎么写，郑老师决定吧。

**Comment by ztl8702** [comment]
有用户对此提出过疑问吗？

**Comment by DDFShanyu** [comment]
改这个是有什么技术性问题吗，我们怎么在这个问题上聊了两天

**Comment by ztl8702** [comment]
是可以改。我只是觉得没必要把这个细节告诉用户。

**Comment by ztl8702** [comment]
[image: Screen Shot 2020-12-09 at 1.54.18 pm.png]
而且写得很长不好看

**Comment by DDFShanyu** [comment]
du53 me21-ang53-ngieng213huak24 mi21-seing213 zuong21-ngi53
&nbsp;


子善（中国账号）
zysieng@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Radium"<notifications@github.com&gt;; 
发送时间: 2020年12月9日(星期三) 下午2:02
收件人: "MindongLab/yngdieng"<yngdieng@noreply.github.com&gt;; 
抄送: "閩東子善"<2056171287@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [MindongLab/yngdieng] 来源的Dictionary of Foochow Dialect表述不严谨 (#969)





 [image: Screen Shot 2020-12-09 at 1.54.18 pm.png]
 而且写得很长不好看
 
 On Wed, 9 Dec 2020 at 13:48, Tianlei Zheng <ztl8702@msn.com&gt; wrote:
 
 &gt; 是可以改。我只是觉得没必要把这个细节告诉用户。
 &gt;
 &gt; On Wed, 9 Dec 2020 at 13:01, ZySieng <notifications@github.com&gt; wrote:
 &gt;
 &gt;&gt; 改这个是有什么技术性问题吗，我们怎么在这个问题上聊了两天
 &gt;&gt;
 &gt;&gt; —
 &gt;&gt; You are receiving this because you commented.
 &gt;&gt; Reply to this email directly, view it on GitHub
 &gt;&gt; <" rel="noopener" target="_blank">https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMindongLab%2Fyngdieng%2Fissues%2F969%23issuecomment-741528202&amp;;data=04%7C01%7C%7Cc7ce6fac0e904a6c6a6008d89bff7a93%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637430868855446050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;amp;sdata=jBcaofSVUKuhJpQhnoQpEAi%2B4d49aC5RKQaUcVubXDY%3D&amp;;reserved=0&amp;gt;,
 &gt;&gt; or unsubscribe
 &gt;&gt; <" rel="noopener" target="_blank">https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAUWWTSIFEELLEIPEMLHHTTST4ACHANCNFSM4URWDPUA&amp;data=04%7C01%7C%7Cc7ce6fac0e904a6c6a6008d89bff7a93%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637430868855446050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=qatoBIHe%2F%2Bq5YrI9stbKe3RmA65f57Q%2FE4RsaLZ3td8%3D&amp;reserved=0&gt;;
 &gt;&gt; .
 &gt;&gt;
 &gt;

**Comment by DDFShanyu** [comment]
写中文会不会好看一点

**Comment by Guanchishan** [comment]
> 是可以改。我只是觉得没必要把这个细节告诉用户。
> 

目前认为需要怎么做？我觉得严谨点也没什么不好。不过如果担心显示不美观，我们可以在详情页里写上它属于index，而在搜索结果页只显示书名，不说他来自index

**Comment by Guanchishan** [comment]
倒是dfd的页数比较迷惑人，这个页数不往榕典上显示就好了

**Comment by DDFShanyu** [comment]
我是觉得写《榕腔注音辞典·目录》，然后在关于页面里面注明一下是DFD的index。这样也不用担心名字太长，也不用担心页数很奇怪。

**Comment by ztl8702** [comment]
已改。
